#!/bin/sh
MODULES="puppetlabs-stdlib puppetlabs-vcsrepo ajjahn-network ajjahn-dns example42-apt example42-mongodb example42-resolver AlexCline-mounts"

for MODULE in $MODULES; do
	puppet module install $MODULE --target-dir=. --modulepath=.
done
