#!/bin/sh
MODULES=" puppetlabs-apt puppetlabs-mysql puppetlabs-stdlib puppetlabs-vcsrepo puppetlabs-nodejs ajjahn-network ajjahn-dns example42-resolver AlexCline-mounts saz-gearman saz-limits pdxcat-collectd"

for MODULE in $MODULES; do
	puppet module install $MODULE --target-dir=. --modulepath=.
done

if [ ! -d mongodb ]; then
	git clone git://github.com/300brand/puppetlabs-mongodb mongodb
fi

if [ ! -d graphite ]; then
	git clone git://github.com/300brand/puppet-graphite graphite
fi

if [ ! -d statsd ]; then
	git clone -b master git://github.com/300brand/puppet-statsd statsd
fi
